# King County House Sales: Pandas Basics

This notebook practices the pandas operations used throughout the project, including data inspection, filtering, sorting, grouping, date handling, summary statistics, and basic column operations.

In [ ]:
from sklearn.datasets import fetch_openml

In [ ]:
house_sales = fetch_openml(
    data_id=42092,
    as_frame=True
)

In [ ]:
house_sales

{'data':                   date  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
 0      20141013T000000         3       1.00         1180      5650     1.0
 1      20141209T000000         3       2.25         2570      7242     2.0
 2      20150225T000000         2       1.00          770     10000     1.0
 3      20141209T000000         4       3.00         1960      5000     1.0
 4      20150218T000000         3       2.00         1680      8080     1.0
 ...                ...       ...        ...          ...       ...     ...
 21608  20140521T000000         3       2.50         1530      1131     3.0
 21609  20150223T000000         4       2.50         2310      5813     2.0
 21610  20140623T000000         2       0.75         1020      1350     2.0
 21611  20150116T000000         3       2.50         1600      2388     2.0
 21612  20141015T000000         2       0.75         1020      1076     2.0

        waterfront  view  condition  grade  sqft_above  sqft_basement  \
 0               0     0          3      7        1180              0
 1               0     0          3      7        2170            400
 2               0     0          3      6         770              0
 3               0     0          5      7        1050            910
 4               0     0          3      8        1680              0
 ...           ...   ...        ...    ...         ...            ...
 21608           0     0          3      8        1530              0
 21609           0     0          3      8        2310              0
 21610           0     0          3      7        1020              0
 21611           0     0          3      8        1600              0
 21612           0     0          3      7        1020              0

        yr_built  yr_renovated zipcode      lat     long  sqft_living15  \
 0          1955             0   98178  47.5112 -122.257           1340
 1          1951          1991   98125  47.7210 -122.319           1690
 2          1933             0   98028  47.7379 -122.233           2720
 3          1965             0   98136  47.5208 -122.393           1360
 4          1987             0   98074  47.6168 -122.045           1800
 ...         ...           ...     ...      ...      ...            ...
 21608      2009             0   98103  47.6993 -122.346           1530
 21609      2014             0   98146  47.5107 -122.362           1830
 21610      2009             0   98144  47.5944 -122.299           1020
 21611      2004             0   98027  47.5345 -122.069           1410
 21612      2008             0   98144  47.5941 -122.299           1020

        sqft_lot15
 0            5650
 1            7639
 2            8062
 3            5000
 4            7503
 ...           ...
 21608        1509
 21609        7200
 21610        2007
 21611        1287
 21612        1357

 [21613 rows x 19 columns],
 'target': 0        221900.0
 1        538000.0
 2        180000.0
 3        604000.0
 4        510000.0
            ...
 21608    360000.0
 21609    400000.0
 21610    402101.0
 21611    400000.0
 21612    325000.0
 Name: price, Length: 21613, dtype: float64,
 'frame':                   date     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
 0      20141013T000000  221900.0         3       1.00         1180      5650
 1      20141209T000000  538000.0         3       2.25         2570      7242
 2      20150225T000000  180000.0         2       1.00          770     10000
 3      20141209T000000  604000.0         4       3.00         1960      5000
 4      20150218T000000  510000.0         3       2.00         1680      8080
 ...                ...       ...       ...        ...          ...       ...
 21608  20140521T000000  360000.0         3       2.50         1530      1131
 21609  20150223T000000  400000.0         4       2.50         2310      5813
 21610  20140623T000000  402101.0         2       0.75         1020      1350
 21611  20150116T000000  400000.0         3       2.50         1600      2388
 21612  20141015T000000  325000.0         2       0.75         1020      1076

        floors  waterfront  view  condition  grade  sqft_above  sqft_basement  \
 0         1.0           0     0          3      7        1180              0
 1         2.0           0     0          3      7        2170            400
 2         1.0           0     0          3      6         770              0
 3         1.0           0     0          5      7        1050            910
 4         1.0           0     0          3      8        1680              0
 ...       ...         ...   ...        ...    ...         ...            ...
 21608     3.0           0     0          3      8        1530              0
 21609     2.0           0     0          3      8        2310              0
 21610     2.0           0     0          3      7        1020              0
 21611     2.0           0     0          3      8        1600              0
 21612     2.0           0     0          3      7        1020              0

        yr_built  yr_renovated zipcode      lat     long  sqft_living15  \
 0          1955             0   98178  47.5112 -122.257           1340
 1          1951          1991   98125  47.7210 -122.319           1690
 2          1933             0   98028  47.7379 -122.233           2720
 3          1965             0   98136  47.5208 -122.393           1360
 4          1987             0   98074  47.6168 -122.045           1800
 ...         ...           ...     ...      ...      ...            ...
 21608      2009             0   98103  47.6993 -122.346           1530
 21609      2014             0   98146  47.5107 -122.362           1830
 21610      2009             0   98144  47.5944 -122.299           1020
 21611      2004             0   98027  47.5345 -122.069           1410
 21612      2008             0   98144  47.5941 -122.299           1020

        sqft_lot15
 0            5650
 1            7639
 2            8062
 3            5000
 4            7503
 ...           ...
 21608        1509
 21609        7200
 21610        2007
 21611        1287
 21612        1357

 [21613 rows x 20 columns],
 'categories': None,
 'feature_names': ['date',
  'bedrooms',
  'bathrooms',
  'sqft_living',
  'sqft_lot',
  'floors',
  'waterfront',
  'view',
  'condition',
  'grade',
  'sqft_above',
  'sqft_basement',
  'yr_built',
  'yr_renovated',
  'zipcode',
  'lat',
  'long',
  'sqft_living15',
  'sqft_lot15'],
 'target_names': ['price'],
 'DESCR': "This dataset contains house sale prices for King County, which includes Seattle. It includes homes sold between May 2014 and May 2015.\n\nIt contains 19 house features plus the price and the id columns, along with 21613 observations.\nIt's a great dataset for evaluating simple regression models.\n\nDownloaded from openml.org.",
 'details': {'id': '42092',
  'name': 'house_sales',
  'version': '2',
  'description_version': '3',
  'format': 'arff',
  'creator': 'https://www.kaggle.com/harlfoxem/',
  'contributor': 'https://www.kaggle.com/harlfoxem/',
  'collection_date': '2016-08-25',
  'upload_date': '2019-08-19T12:09:01',
  'language': 'English',
  'licence': 'CC0 Public Domain',
  'url': 'https://openml.org/data/v1/download/21578898/house_sales.arff',
  'parquet_url': 'https://data.openml.org/datasets/0004/42092/dataset_42092.pq',
  'file_id': '21578898',
  'default_target_attribute': 'price',
  'row_id_attribute': 'id',
  'version_label': '0.1',
  'visibility': 'public',
  'original_data_url': 'https://www.kaggle.com/harlfoxem/housesalesprediction',
  'status': 'active',
  'processing_date': '2019-08-19 12:09:03',
  'md5_checksum': '0208b93d87877d917afdc43987e7b4b4'},
 'url': 'https://www.openml.org/d/42092'}

In [ ]:
houses = house_sales.frame.copy()

In [ ]:
houses

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

# tables in python: pandas dataframe

In [ ]:
type(houses)

pandas.core.frame.DataFrame

In [ ]:
import pandas

In [ ]:
houses.shape

(21613, 20)

In [ ]:
houses.index

RangeIndex(start=0, stop=21613, step=1)

In [ ]:
houses.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [ ]:
houses.condition

0        3
1        3
2        3
3        5
4        3
        ..
21608    3
21609    3
21610    3
21611    3
21612    3
Name: condition, Length: 21613, dtype: int64

In [ ]:
houses['condition']

0        3
1        3
2        3
3        5
4        3
        ..
21608    3
21609    3
21610    3
21611    3
21612    3
Name: condition, Length: 21613, dtype: int64

In [ ]:
houses['condition'].unique()

array([3, 5, 4, 1, 2])

In [ ]:
houses.condition.value_counts()

condition
3    14031
4     5679
5     1701
2      172
1       30
Name: count, dtype: int64

In [ ]:
houses.grade

0        7
1        7
2        6
3        7
4        8
        ..
21608    8
21609    8
21610    7
21611    8
21612    7
Name: grade, Length: 21613, dtype: int64

In [ ]:
houses.grade.unique()

array([ 7,  6,  8, 11,  9,  5, 10, 12,  4,  3, 13,  1])

In [ ]:
houses.grade.value_counts()

grade
7     8981
8     6068
9     2615
6     2038
10    1134
11     399
5      242
12      90
4       29
13      13
3        3
1        1
Name: count, dtype: int64

In [ ]:
houses.head(10)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,3,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,3,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,3,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
9,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,3,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570

In [ ]:
houses.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [ ]:
houses.tail()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [ ]:
houses.tail(10)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21603,20140825T000000,507250.0,3,2.50,2270,5536,2.0,0,0,3,8,2270,0,2003,0,98065,47.5389,-121.881,2270,5731
21604,20150126T000000,429000.0,3,2.00,1490,1126,3.0,0,0,3,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
21605,20141014T000000,610685.0,4,2.50,2520,6023,2.0,0,0,3,9,2520,0,2014,0,98056,47.5137,-122.167,2520,6023
21606,20150326T000000,1007500.0,4,3.50,3510,7200,2.0,0,0,3,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200
21607,20150219T000000,475000.0,3,2.50,1310,1294,2.0,0,0,3,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [ ]:
houses

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [ ]:
houses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           21613 non-null  object
 1   price          21613 non-null  float64
 2   bedrooms       21613 non-null  int64
 3   bathrooms      21613 non-null  float64
 4   sqft_living    21613 non-null  int64
 5   sqft_lot       21613 non-null  int64
 6   floors         21613 non-null  float64
 7   waterfront     21613 non-null  int64
 8   view           21613 non-null  int64
 9   condition      21613 non-null  int64
 10  grade          21613 non-null  int64
 11  sqft_above     21613 non-null  int64
 12  sqft_basement  21613 non-null  int64
 13  yr_built       21613 non-null  int64
 14  yr_renovated   21613 non-null  int64
 15  zipcode        21613 non-null  category
 16  lat            21613 non-null  float64
 17  long           21613 non-null  float64
 18  sqft_living15  21613 non-null  int64
 19  sqft_lot15     21613 non-null  int64
dtypes: category(1), float64(5), int64(13), object(1)
memory usage: 3.2+ MB

# datatype:

integer int: integer

floating-point float: decimal

string string: "" == ''

boolean boolean: True/False

In [ ]:
houses.loc[0,'date']

'20141013T000000'

In [ ]:
type(houses.loc[0,'date'])

str

In [ ]:
houses.loc[0,'zipcode']

'98178'

In [ ]:
type(houses.loc[0,'zipcode'])

str



houses.date shorthand, sometimes don't work

houses['date'] valid, always work

In [ ]:
houses[['date','zipcode']]

                  date zipcode
0      20141013T000000   98178
1      20141209T000000   98125
2      20150225T000000   98028
3      20141209T000000   98136
4      20150218T000000   98074
...                ...     ...
21608  20140521T000000   98103
21609  20150223T000000   98146
21610  20140623T000000   98144
21611  20150116T000000   98027
21612  20141015T000000   98144

[21613 rows x 2 columns]

slicing: houses.loc[row_name, column_name]

In [ ]:
houses.loc[0,:]

date             20141013T000000
price                   221900.0
bedrooms                       3
bathrooms                    1.0
sqft_living                 1180
sqft_lot                    5650
floors                       1.0
waterfront                     0
view                           0
condition                      3
grade                          7
sqft_above                  1180
sqft_basement                  0
yr_built                    1955
yr_renovated                   0
zipcode                    98178
lat                      47.5112
long                    -122.257
sqft_living15               1340
sqft_lot15                  5650
Name: 0, dtype: object

In [ ]:
houses.loc[0,'zipcode']

'98178'

In [ ]:
houses.loc[0,['zipcode','date','yr_built']]

zipcode               98178
date        20141013T000000
yr_built               1955
Name: 0, dtype: object

In [ ]:
houses.loc[[0,5,10],['zipcode','date','yr_built']]

   zipcode             date  yr_built
0    98178  20141013T000000      1955
5    98053  20140512T000000      2001
10   98007  20150403T000000      1965

In [ ]:
houses.loc[0,'zipcode']

'98178'

slicing: houses.iloc[row_number, column_number]

in this dataset, row_name==row_number

In [ ]:
houses.iloc[0,0]

'20141013T000000'

In [ ]:
houses.iloc[[0,5,10],[0,10,13]]

               date  grade  yr_built
0   20141013T000000      7      1955
5   20140512T000000     11      2001
10  20150403T000000      8      1965

In [ ]:
houses.loc[0:9]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,3,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,3,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,3,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
9,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,3,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570

In [ ]:
houses.iloc[0:9]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,3,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,3,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,3,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113

slicing in python: includes the start but excludes the end a:b

> add a block quote symbol

In [ ]:
a = [10, 30,'T','R',"S"]

In [ ]:
a[0]

10

In [ ]:
a[1]

30

In [ ]:
a[2]

'T'

In [ ]:
a[3]

'R'

In [ ]:
a[4]

'S'

In [ ]:
a[0:2]

[10, 30]

In [ ]:
a[-3:-1]

['T', 'R']

In [ ]:
a

[10, 30, 'T', 'R', 'S']

In [ ]:
a[-1]

'S'

In [ ]:
a[-2]

'R'

In [ ]:
a[-3]

'T'

In [ ]:
a[-3:-1]

['T', 'R']

In [ ]:
houses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           21613 non-null  object
 1   price          21613 non-null  float64
 2   bedrooms       21613 non-null  int64
 3   bathrooms      21613 non-null  float64
 4   sqft_living    21613 non-null  int64
 5   sqft_lot       21613 non-null  int64
 6   floors         21613 non-null  float64
 7   waterfront     21613 non-null  int64
 8   view           21613 non-null  int64
 9   condition      21613 non-null  int64
 10  grade          21613 non-null  int64
 11  sqft_above     21613 non-null  int64
 12  sqft_basement  21613 non-null  int64
 13  yr_built       21613 non-null  int64
 14  yr_renovated   21613 non-null  int64
 15  zipcode        21613 non-null  category
 16  lat            21613 non-null  float64
 17  long           21613 non-null  float64
 18  sqft_living15  21613 non-null  int64
 19  sqft_lot15     21613 non-null  int64
dtypes: category(1), float64(5), int64(13), object(1)
memory usage: 3.2+ MB

houses.describe(): summary statistic

In [ ]:
houses.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,47.560053,-122.213896,1986.552492,12768.455652
std,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,0.138564,0.140828,685.391304,27304.179631
min,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,47.155900,-122.519000,399.000000,651.000000
25%,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,47.678000,-122.125000,2360.000000,10083.000000
max,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,47.777600,-121.315000,6210.000000,871200.000000

In [ ]:
houses.waterfront.value_counts(ascending=True)

waterfront
1      163
0    21450
Name: count, dtype: int64

In [ ]:
houses.waterfront.value_counts()

waterfront
0    21450
1      163
Name: count, dtype: int64

# mean of a binary variable (0,1): proportion of 1s

In [ ]:
houses.waterfront

0        0
1        0
2        0
3        0
4        0
        ..
21608    0
21609    0
21610    0
21611    0
21612    0
Name: waterfront, Length: 21613, dtype: int64

ordinal variable: ordered variable, values only represent relative concepts

1 is better than 0, and 2 is better than 1

but the difference between 1 and 0 is not equal to the difference between 2 and 1

In [ ]:
houses.view.value_counts()

view
0    19489
2      963
3      510
1      332
4      319
Name: count, dtype: int64

In [ ]:
houses.condition.value_counts()

condition
3    14031
4     5679
5     1701
2      172
1       30
Name: count, dtype: int64

In [ ]:
houses.grade.value_counts()

grade
7     8981
8     6068
9     2615
6     2038
10    1134
11     399
5      242
12      90
4       29
13      13
3        3
1        1
Name: count, dtype: int64

# Conditional filtering

In [ ]:
houses.price.describe()

count    2.161300e+04
mean     5.400881e+05
std      3.671272e+05
min      7.500000e+04
25%      3.219500e+05
50%      4.500000e+05
75%      6.450000e+05
max      7.700000e+06
Name: price, dtype: float64

In [ ]:
cond = houses.price>1000000

In [ ]:
cond

0        False
1        False
2        False
3        False
4        False
         ...
21608    False
21609    False
21610    False
21611    False
21612    False
Name: price, Length: 21613, dtype: bool

In [ ]:
cond.sum()

np.int64(1465)

In [ ]:
expensive_houses = houses[cond]

In [ ]:
expensive_houses.shape

(1465, 20)

In [ ]:
expensive_houses.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
count,1.465000e+03,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000
mean,1.535623e+06,4.066212,3.166212,3799.971331,23321.540614,1.810239,0.070990,1.224573,3.473720,9.758362,3110.963823,689.007509,1974.640273,242.867577,47.617435,-122.223313,3063.655290,18088.141297
std,6.286524e+05,0.915328,0.871099,1190.979462,57138.864260,0.487372,0.256895,1.526433,0.711555,1.217041,1130.448013,690.708055,32.565900,653.289335,0.060159,0.114131,851.084127,36814.170879
min,1.000750e+06,0.000000,0.000000,1330.000000,609.000000,1.000000,0.000000,0.000000,1.000000,6.000000,1040.000000,0.000000,1900.000000,0.000000,47.329300,-122.451000,1050.000000,1224.000000
25%,1.150000e+06,4.000000,2.500000,2980.000000,6906.000000,1.500000,0.000000,0.000000,3.000000,9.000000,2230.000000,0.000000,1951.000000,0.000000,47.574400,-122.292000,2460.000000,6349.000000
50%,1.326000e+06,4.000000,3.250000,3650.000000,10900.000000,2.000000,0.000000,0.000000,3.000000,10.000000,2910.000000,670.000000,1985.000000,0.000000,47.627200,-122.223000,3000.000000,10476.000000
75%,1.691000e+06,5.000000,3.500000,4370.000000,18815.000000,2.000000,0.000000,3.000000,4.000000,11.000000,3850.000000,1140.000000,2003.000000,0.000000,47.652600,-122.158000,3620.000000,16893.000000
max,7.700000e+06,10.000000,8.000000,13540.000000,920423.000000,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,47.773500,-121.731000,6210.000000,858132.000000

In [ ]:
cond = (houses.price>1000000) & (houses.bedrooms>=5) & (houses.bathrooms>=5)

In [ ]:
cond.sum()

np.int64(33)

In [ ]:
exp_h = houses[cond]

In [ ]:
exp_h.shape

(33, 20)

In [ ]:
exp_h.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
count,3.300000e+01,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000
mean,3.090833e+06,5.575758,5.787879,6927.272727,58280.393939,1.969697,0.121212,1.575758,3.151515,11.454545,5506.969697,1420.303030,1993.545455,303.000000,47.605176,-122.161818,3618.636364,41783.636364
std,1.754478e+06,1.090593,0.852664,2238.227916,81643.304535,0.373735,0.331434,1.768303,0.441674,1.301223,1582.508856,1309.509653,23.457529,728.151984,0.072430,0.131781,982.838104,64709.786209
min,1.148000e+06,5.000000,5.000000,3410.000000,8118.000000,1.000000,0.000000,0.000000,3.000000,8.000000,2500.000000,0.000000,1910.000000,0.000000,47.380000,-122.408000,1800.000000,6477.000000
25%,1.681000e+06,5.000000,5.250000,5090.000000,18200.000000,2.000000,0.000000,0.000000,3.000000,11.000000,4320.000000,0.000000,1998.000000,0.000000,47.569200,-122.236000,2910.000000,10454.000000
50%,2.888000e+06,5.000000,5.500000,6880.000000,23985.000000,2.000000,0.000000,0.000000,3.000000,12.000000,5240.000000,1110.000000,2001.000000,0.000000,47.609400,-122.210000,3430.000000,19329.000000
75%,4.208000e+06,6.000000,6.000000,8000.000000,42840.000000,2.000000,0.000000,3.000000,3.000000,12.000000,6290.000000,2120.000000,2006.000000,0.000000,47.629800,-122.084000,4320.000000,26788.000000
max,7.700000e+06,10.000000,8.000000,13540.000000,307752.000000,3.000000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2014.000000,2009.000000,47.761500,-121.779000,6110.000000,256803.000000

In [ ]:
cond = (((houses.price>1000000) | (houses.bedrooms>=5)) & (houses.bathrooms>=5))

In [ ]:
exp_h2 = houses[cond]

In [ ]:
exp_h2.shape

(63, 20)

In [ ]:
houses.zipcode.unique()

['98178', '98125', '98028', '98136', '98074', ..., '98072', '98188', '98014', '98055', '98039']
Length: 70
Categories (70, object): ['98001', '98002', '98003', '98004', ..., '98178', '98188', '98198', '98199']

In [ ]:
cond = houses.zipcode.isin(['98178', '98125', '98028'])

In [ ]:
zip_h = houses[cond]

In [ ]:
zip_h.zipcode.unique()

['98178', '98125', '98028']
Categories (70, object): ['98001', '98002', '98003', '98004', ..., '98178', '98188', '98198', '98199']

# Create a new column

In [ ]:
houses.price.describe()

count    2.161300e+04
mean     5.400881e+05
std      3.671272e+05
min      7.500000e+04
25%      3.219500e+05
50%      4.500000e+05
75%      6.450000e+05
max      7.700000e+06
Name: price, dtype: float64

In [ ]:
houses['price_thousand'] = houses.price/1000

In [ ]:
houses.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15', 'price_thousand'],
      dtype='object')

In [ ]:
houses.shape

(21613, 21)

In [ ]:
houses[['price','price_thousand']]

          price  price_thousand
0      221900.0         221.900
1      538000.0         538.000
2      180000.0         180.000
3      604000.0         604.000
4      510000.0         510.000
...         ...             ...
21608  360000.0         360.000
21609  400000.0         400.000
21610  402101.0         402.101
21611  400000.0         400.000
21612  325000.0         325.000

[21613 rows x 2 columns]

In [ ]:
houses['price_per_sqft'] = houses["price"] / houses["sqft_living"]

In [ ]:
houses.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15', 'price_thousand', 'price_per_sqft'],
      dtype='object')

In [ ]:
houses.shape

(21613, 22)

# Convert dates

In [ ]:
type(houses.date[0])

str

In [ ]:
import pandas as pd

In [ ]:
a = pd.to_datetime(houses.date)

In [ ]:
a

0       2014-10-13
1       2014-12-09
2       2015-02-25
3       2014-12-09
4       2015-02-18
           ...
21608   2014-05-21
21609   2015-02-23
21610   2014-06-23
21611   2015-01-16
21612   2014-10-15
Name: date, Length: 21613, dtype: datetime64[ns]

In [ ]:
houses.date

0        20141013T000000
1        20141209T000000
2        20150225T000000
3        20141209T000000
4        20150218T000000
              ...
21608    20140521T000000
21609    20150223T000000
21610    20140623T000000
21611    20150116T000000
21612    20141015T000000
Name: date, Length: 21613, dtype: object

In [ ]:
houses['date'] = a

In [ ]:
houses.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price_thousand,price_per_sqft
0,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,3,...,0,1955,0,98178,47.5112,-122.257,1340,5650,221.9,188.050847
1,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,3,...,400,1951,1991,98125,47.7210,-122.319,1690,7639,538.0,209.338521
2,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,3,...,0,1933,0,98028,47.7379,-122.233,2720,8062,180.0,233.766234
3,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,5,...,910,1965,0,98136,47.5208,-122.393,1360,5000,604.0,308.163265
4,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,3,...,0,1987,0,98074,47.6168,-122.045,1800,7503,510.0,303.571429

In [ ]:
houses['sale_year'] = houses.date.dt.year

In [ ]:
houses.sale_year

0        2014
1        2014
2        2015
3        2014
4        2015
         ...
21608    2014
21609    2015
21610    2014
21611    2015
21612    2014
Name: sale_year, Length: 21613, dtype: int32

In [ ]:
houses['sale_month'] = houses.date.dt.month

In [ ]:
houses['house_age'] = houses.sale_year - houses.yr_built

In [ ]:
houses['house_age'].describe()

count    21613.000000
mean        43.317818
std         29.375493
min         -1.000000
25%         18.000000
50%         40.000000
75%         63.000000
max        115.000000
Name: house_age, dtype: float64

In [ ]:
houses.yr_renovated.describe()

count    21613.000000
mean        84.402258
std        401.679240
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       2015.000000
Name: yr_renovated, dtype: float64

In [ ]:
houses['renovated'] = houses.yr_renovated>0

In [ ]:
houses['renovated']

0        False
1         True
2        False
3        False
4        False
         ...
21608    False
21609    False
21610    False
21611    False
21612    False
Name: renovated, Length: 21613, dtype: bool

sum of the values in a boolean column = number of True values

In [ ]:
houses['renovated'].sum()

np.int64(914)

value_counts(): count for each category

In [ ]:
houses['renovated'].value_counts()

renovated
False    20699
True       914
Name: count, dtype: int64

# Sorting sort

In [ ]:
a = houses.sort_values("price", ascending=False)

In [ ]:
a

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
7252,20141013T000000,7700000.0,6,8.00,12050,27600,2.5,0,3,4,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800
3914,20140611T000000,7062500.0,5,4.50,10040,37325,2.0,1,2,3,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930,25449
9254,20140919T000000,6885000.0,6,7.75,9890,31374,2.0,0,4,3,13,8860,1030,2001,0,98039,47.6305,-122.240,4540,42730
4411,20140804T000000,5570000.0,5,5.75,9200,35069,2.0,0,0,3,13,6200,3000,2001,0,98039,47.6289,-122.233,3560,24345
1448,20150413T000000,5350000.0,5,5.00,8000,23985,2.0,0,4,3,12,6720,1280,2009,0,98004,47.6232,-122.220,4600,21750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8274,20141105T000000,82000.0,3,1.00,860,10426,1.0,0,0,3,6,860,0,1954,0,98146,47.4987,-122.341,1140,11250
16198,20150324T000000,81000.0,2,1.00,730,9975,1.0,0,0,1,5,730,0,1943,0,98168,47.4808,-122.315,860,9000
465,20140523T000000,80000.0,1,0.75,430,5050,1.0,0,0,2,4,430,0,1912,0,98014,47.6499,-121.909,1200,7500
15293,20140506T000000,78000.0,2,1.00,780,16344,1.0,0,0,1,5,780,0,1942,0,98168,47.4739,-122.280,1700,10387
1149,20150217T000000,75000.0,1,0.00,670,43377,1.0,0,0,3,3,670,0,1966,0,98022,47.2638,-121.906,1160,42882

In [ ]:
houses

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [ ]:
b = houses.sort_values(['zipcode','price'], ascending=[True, False])

In [ ]:
b

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
6628,20140930T000000,850000.0,4,2.75,5440,239580,1.0,0,0,2,9,2720,2720,1969,0,98001,47.3540,-122.293,1970,40392
6145,20150402T000000,639900.0,4,2.50,3380,75794,2.0,0,0,3,10,3380,0,1997,0,98001,47.3511,-122.266,3710,17913
18288,20140919T000000,637000.0,4,3.50,4083,68377,2.0,0,0,3,10,4083,0,2005,0,98001,47.3114,-122.262,2430,41382
18807,20140709T000000,625000.0,3,1.75,3160,76230,1.0,0,0,4,8,2160,1000,1978,0,98001,47.2740,-122.287,1990,45789
9318,20141006T000000,571500.0,4,2.25,2810,25990,2.0,0,0,3,8,1860,950,1959,0,98001,47.2993,-122.293,2020,16140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8458,20141105T000000,340000.0,2,1.75,1010,1461,1.0,0,0,3,7,670,340,2003,0,98199,47.6515,-122.400,1500,2499
17377,20150326T000000,334000.0,2,1.00,900,1818,2.0,0,0,4,7,900,0,1945,0,98199,47.6485,-122.397,1570,1830
274,20141124T000000,331000.0,3,1.75,1080,1306,1.0,0,0,3,7,580,500,1954,2003,98199,47.6601,-122.400,1440,2225
3900,20141008T000000,330000.0,2,1.00,880,1753,2.0,0,0,4,7,880,0,1945,0,98199,47.6475,-122.397,1010,1748
4708,20150109T000000,323000.0,2,1.00,880,1712,2.0,0,0,4,7,880,0,1945,0,98199,47.6475,-122.397,1360,1748

In [ ]:
b[['zipcode','price']]

      zipcode     price
6628    98001  850000.0
6145    98001  639900.0
18288   98001  637000.0
18807   98001  625000.0
9318    98001  571500.0
...       ...       ...
8458    98199  340000.0
17377   98199  334000.0
274     98199  331000.0
3900    98199  330000.0
4708    98199  323000.0

[21613 rows x 2 columns]

In [ ]:
houses.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,47.560053,-122.213896,1986.552492,12768.455652
std,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,0.138564,0.140828,685.391304,27304.179631
min,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,47.155900,-122.519000,399.000000,651.000000
25%,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,47.678000,-122.125000,2360.000000,10083.000000
max,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,47.777600,-121.315000,6210.000000,871200.000000

# Calculate common statistics

In [ ]:
houses.price.mean()

np.float64(540088.1417665294)

In [ ]:
houses.price.median()

450000.0

Variance: measures the spread/dispersion of the data

 $\sigma_Y^2=\frac{1}{n} \sum_{i=1}^n\left(Y_i-\bar{Y}\right)^2$

 Mean: the center of the data Y_bar

In [ ]:
houses.price.std()

367127.1964826997

In [ ]:
houses.price.min()

75000.0

In [ ]:
houses.price.max()

7700000.0

# Find the row containing the maximum value

cond = houses.price==highest_price can find all of the most expensive houses

highest_price_index = houses.price.idxmax() can only find one of the most expensive houses

In [ ]:
highest_price = houses.price.max()

In [ ]:
cond = houses.price==highest_price

In [ ]:
houses[cond]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
7252,20141013T000000,7700000.0,6,8.0,12050,27600,2.5,0,3,4,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800

In [ ]:
highest_price_index = houses.price.idxmax()

In [ ]:
highest_price_index

7252

In [ ]:
houses.loc[highest_price_index]

date             20141013T000000
price                  7700000.0
bedrooms                       6
bathrooms                    8.0
sqft_living                12050
sqft_lot                   27600
floors                       2.5
waterfront                     0
view                           3
condition                      4
grade                         13
sqft_above                  8570
sqft_basement               3480
yr_built                    1910
yr_renovated                1987
zipcode                    98102
lat                      47.6298
long                    -122.323
sqft_living15               3940
sqft_lot15                  8800
Name: 7252, dtype: object

function value_counts()

In [ ]:
houses.bedrooms.value_counts(ascending=True).sort_index(ascending=False)

bedrooms
33       1
11       1
10       3
9        6
8       13
7       38
6      272
5     1601
4     6882
3     9824
2     2760
1      199
0       13
Name: count, dtype: int64

In [ ]:
houses.view.value_counts()

view
0    19489
2      963
3      510
1      332
4      319
Name: count, dtype: int64

In [ ]:
houses.view.value_counts(normalize=True)

view
0    0.901726
2    0.044557
3    0.023597
1    0.015361
4    0.014760
Name: proportion, dtype: float64

In [ ]:
houses.view.value_counts(normalize=True).sort_index()

view
0    0.901726
1    0.015361
2    0.044557
3    0.023597
4    0.014760
Name: proportion, dtype: float64

In [ ]:
houses.view.value_counts(normalize=True).sort_index()*100

view
0    90.172581
1     1.536113
2     4.455652
3     2.359691
4     1.475964
Name: proportion, dtype: float64

# groupby

In [ ]:
houses.groupby('bedrooms').price.mean()

bedrooms
0     4.095038e+05
1     3.176429e+05
2     4.013727e+05
3     4.662321e+05
4     6.354195e+05
5     7.865998e+05
6     8.255206e+05
7     9.511847e+05
8     1.105077e+06
9     8.939998e+05
10    8.193333e+05
11    5.200000e+05
33    6.400000e+05
Name: price, dtype: float64

In [ ]:
houses.groupby('bedrooms').price.median()

bedrooms
0     288000.0
1     299000.0
2     374000.0
3     413000.0
4     549997.5
5     620000.0
6     650000.0
7     728580.0
8     700000.0
9     817000.0
10    660000.0
11    520000.0
33    640000.0
Name: price, dtype: float64

agg: aggregate

In [ ]:
houses.groupby('bedrooms').price.agg(['count','mean','median','min','max'])

          count          mean    median       min        max
bedrooms
0            13  4.095038e+05  288000.0  139950.0  1295650.0
1           199  3.176429e+05  299000.0   75000.0  1247000.0
2          2760  4.013727e+05  374000.0   78000.0  3278000.0
3          9824  4.662321e+05  413000.0   82000.0  3800000.0
4          6882  6.354195e+05  549997.5  100000.0  4489000.0
5          1601  7.865998e+05  620000.0  133000.0  7062500.0
6           272  8.255206e+05  650000.0  175000.0  7700000.0
7            38  9.511847e+05  728580.0  280000.0  3200000.0
8            13  1.105077e+06  700000.0  340000.0  3300000.0
9             6  8.939998e+05  817000.0  450000.0  1400000.0
10            3  8.193333e+05  660000.0  650000.0  1148000.0
11            1  5.200000e+05  520000.0  520000.0   520000.0
33            1  6.400000e+05  640000.0  640000.0   640000.0

In [ ]:
grade_summary = houses.groupby("grade").price.agg(['count','mean','median','min','max'])

In [ ]:
grade_summary

       count          mean     median        min        max
grade
1          1  1.420000e+05   142000.0   142000.0   142000.0
3          3  2.056667e+05   262000.0    75000.0   280000.0
4         29  2.143810e+05   205000.0    80000.0   435000.0
5        242  2.485240e+05   228700.0    78000.0   795000.0
6       2038  3.019196e+05   275276.5    82000.0  1200000.0
7       8981  4.025903e+05   375000.0    90000.0  2050000.0
8       6068  5.428528e+05   510000.0   140000.0  3070000.0
9       2615  7.735132e+05   720000.0   230000.0  2700000.0
10      1134  1.071771e+06   914327.0   316000.0  3600000.0
11       399  1.496842e+06  1284000.0   420000.0  7062500.0
12        90  2.191222e+06  1817500.0   835000.0  5350000.0
13        13  3.709615e+06  2983000.0  1780000.0  7700000.0

In [ ]:
grade_summary.to_csv("grade_summary.csv")

In [ ]:
type(grade_summary)

pandas.core.frame.DataFrame

In [ ]:
grade_summary.sort_values("median",ascending=False)

       count          mean     median        min        max
grade
13        13  3.709615e+06  2983000.0  1780000.0  7700000.0
12        90  2.191222e+06  1817500.0   835000.0  5350000.0
11       399  1.496842e+06  1284000.0   420000.0  7062500.0
10      1134  1.071771e+06   914327.0   316000.0  3600000.0
9       2615  7.735132e+05   720000.0   230000.0  2700000.0
8       6068  5.428528e+05   510000.0   140000.0  3070000.0
7       8981  4.025903e+05   375000.0    90000.0  2050000.0
6       2038  3.019196e+05   275276.5    82000.0  1200000.0
3          3  2.056667e+05   262000.0    75000.0   280000.0
5        242  2.485240e+05   228700.0    78000.0   795000.0
4         29  2.143810e+05   205000.0    80000.0   435000.0
1          1  1.420000e+05   142000.0   142000.0   142000.0

# Find the ZIP code with the highest house prices

In [ ]:
houses.groupby('zipcode').price.mean()

zipcode
98001    2.808047e+05
98002    2.342840e+05
98003    2.941113e+05
98004    1.355927e+06
98005    8.101649e+05
             ...
98177    6.761854e+05
98178    3.106128e+05
98188    2.890783e+05
98198    3.028789e+05
98199    7.918208e+05
Name: price, Length: 70, dtype: float64

idx: index

In [ ]:
houses.groupby('zipcode').price.mean().idxmax()

'98039'

In [ ]:
houses.groupby('zipcode').price.mean().sort_values()

zipcode
98002    2.342840e+05
98168    2.403284e+05
98032    2.512962e+05
98001    2.808047e+05
98148    2.849086e+05
             ...
98102    9.012583e+05
98112    1.095499e+06
98040    1.194230e+06
98004    1.355927e+06
98039    2.160607e+06
Name: price, Length: 70, dtype: float64

In [ ]:
zipcode_summary = houses.groupby('zipcode').price.agg(['count','mean','median'])

In [ ]:
zipcode_summary2 = zipcode_summary[zipcode_summary['count']>100]

In [ ]:
zipcode_summary.shape

(70, 3)

In [ ]:
zipcode_summary2.shape

(66, 3)

In [ ]:
zipcode_summary

         count          mean     median
zipcode
98001      362  2.808047e+05   260000.0
98002      199  2.342840e+05   235000.0
98003      280  2.941113e+05   267475.0
98004      317  1.355927e+06  1150000.0
98005      168  8.101649e+05   765475.0
...        ...           ...        ...
98177      255  6.761854e+05   554000.0
98178      262  3.106128e+05   278277.0
98188      136  2.890783e+05   264000.0
98198      280  3.028789e+05   265000.0
98199      317  7.918208e+05   689800.0

[70 rows x 3 columns]

In [ ]:
zipcode_summary['count']

zipcode
98001    362
98002    199
98003    280
98004    317
98005    168
        ...
98177    255
98178    262
98188    136
98198    280
98199    317
Name: count, Length: 70, dtype: int64

In [ ]:
zipcode_summary2.sort_values('median')

         count          mean     median
zipcode
98002      199  2.342840e+05   235000.0
98168      269  2.403284e+05   235000.0
98032      125  2.512962e+05   249000.0
98001      362  2.808047e+05   260000.0
98188      136  2.890783e+05   264000.0
...        ...           ...        ...
98006      498  8.596848e+05   760184.5
98005      168  8.101649e+05   765475.0
98112      269  1.095499e+06   915000.0
98040      282  1.194230e+06   993750.0
98004      317  1.355927e+06  1150000.0

[66 rows x 3 columns]

In [ ]:
bedroom_summary = (
    houses.groupby("bedrooms")["price"]
    .mean())

In [ ]:
type(bedroom_summary)

pandas.core.series.Series

In [ ]:
bedroom_summary.index

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 33], dtype='int64', name='bedrooms')

In [ ]:
bedroom_summary

bedrooms
0     4.095038e+05
1     3.176429e+05
2     4.013727e+05
3     4.662321e+05
4     6.354195e+05
5     7.865998e+05
6     8.255206e+05
7     9.511847e+05
8     1.105077e+06
9     8.939998e+05
10    8.193333e+05
11    5.200000e+05
33    6.400000e+05
Name: price, dtype: float64

In [ ]:
bedroom_summary = bedroom_summary.reset_index()

In [ ]:
bedroom_summary

    bedrooms         price
0          0  4.095038e+05
1          1  3.176429e+05
2          2  4.013727e+05
3          3  4.662321e+05
4          4  6.354195e+05
5          5  7.865998e+05
6          6  8.255206e+05
7          7  9.511847e+05
8          8  1.105077e+06
9          9  8.939998e+05
10        10  8.193333e+05
11        11  5.200000e+05
12        33  6.400000e+05

In [ ]:
bedroom_summary.index

RangeIndex(start=0, stop=13, step=1)

# Check whether there are duplicate values

In [ ]:
houses.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
21608    False
21609    False
21610    False
21611    False
21612    False
Length: 21613, dtype: bool

In [ ]:
houses.duplicated().sum()

np.int64(0)

In [ ]:
houses.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [ ]:
a = houses.date.duplicated()

In [ ]:
 houses.date[a]

3        20141209T000000
14       20150312T000000
31       20141201T000000
32       20140624T000000
33       20141110T000000
              ...
21608    20140521T000000
21609    20150223T000000
21610    20140623T000000
21611    20150116T000000
21612    20141015T000000
Name: date, Length: 21241, dtype: object

# Rename columns

In [ ]:
houses.rename(columns={"price":"sale_price",'date':'Python_date'})

,Python_date,sale_price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [ ]:
houses

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

# Delete certain columns

In [ ]:
houses.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [ ]:
houses.drop(columns=['lat','long'])

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,1020,1357

In [ ]:
houses.drop(columns=['lat','long']).columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'sqft_living15',
       'sqft_lot15'],
      dtype='object')

In [ ]:
houses

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [ ]:
houses = houses.drop(columns=['lat','long'])

In [ ]:
houses.drop(index=0)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,sqft_living15,sqft_lot15
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,1360,5000
4,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,1800,7503
5,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,4760,101930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,1020,1357

In [ ]:
houses.drop(index=[0,4,6])

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,sqft_living15,sqft_lot15
1,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,1690,7639
2,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,2720,8062
3,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,1360,5000
5,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,4760,101930
7,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,3,7,1060,0,1963,0,98198,1650,9711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,1530,1509
21609,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,1830,7200
21610,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,1020,2007
21611,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,1410,1287
21612,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,1020,1357

In [ ]:
sample100 = houses.sample(100, random_state=42)

In [ ]:
sample100.to_csv('sample100.csv')

In [ ]:
sample5 = houses.sample(5, random_state=42)

In [ ]:
sample5

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,sqft_living15,sqft_lot15
735,20141006T000000,365000.0,4,2.25,2070,8893,2.0,0,0,4,8,2070,0,1986,0,98058,2390,7700
2830,20140821T000000,865000.0,5,3.00,2900,6730,1.0,0,0,5,8,1830,1070,1977,0,98115,2370,6283
4106,20140815T000000,1038000.0,4,2.50,3770,10893,2.0,0,2,3,11,3770,0,1997,0,98006,3710,9685
16218,20150331T000000,1490000.0,3,3.50,4560,14608,2.0,0,2,3,12,4560,0,1990,0,98034,4050,14226
19964,20140714T000000,711000.0,3,2.50,2550,5376,2.0,0,0,3,9,2550,0,2004,0,98052,2250,4050

In [ ]:
sample5 = houses.sample(5, random_state=42)

In [ ]:
sample5

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,sqft_living15,sqft_lot15
735,20141006T000000,365000.0,4,2.25,2070,8893,2.0,0,0,4,8,2070,0,1986,0,98058,2390,7700
2830,20140821T000000,865000.0,5,3.00,2900,6730,1.0,0,0,5,8,1830,1070,1977,0,98115,2370,6283
4106,20140815T000000,1038000.0,4,2.50,3770,10893,2.0,0,2,3,11,3770,0,1997,0,98006,3710,9685
16218,20150331T000000,1490000.0,3,3.50,4560,14608,2.0,0,2,3,12,4560,0,1990,0,98034,4050,14226
19964,20140714T000000,711000.0,3,2.50,2550,5376,2.0,0,0,3,9,2550,0,2004,0,98052,2250,4050

In [ ]:
sample5 = houses.sample(5)

In [ ]:
sample5

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,sqft_living15,sqft_lot15
11118,20140827T000000,545000.0,4,2.25,2390,40510,1.0,0,0,4,8,2390,0,1969,0,98072,3200,36989
13311,20141009T000000,527950.0,4,1.75,1760,3600,1.0,0,0,5,7,880,880,1926,0,98103,1500,5580
13263,20150210T000000,466200.0,3,1.50,1340,8856,1.0,0,0,4,7,1340,0,1959,0,98008,1850,8740
8489,20150303T000000,674000.0,5,1.75,2110,5000,1.5,0,0,4,7,1250,860,1946,0,98115,1720,5000
19272,20140721T000000,1800000.0,4,2.50,3320,8325,2.5,0,0,5,10,3320,0,1905,0,98112,3680,6050

In [ ]:
sample5 = houses.sample(5)

In [ ]:
sample5

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,sqft_living15,sqft_lot15
10752,20141016T000000,200000.0,2,1.75,910,2693,1.0,0,0,3,6,910,0,2003,0,98038,1360,2693
5267,20140530T000000,349900.0,3,2.50,2200,7278,2.0,0,0,3,8,2200,0,1990,0,98058,2190,8580
14007,20141007T000000,539950.0,4,2.75,2910,9000,1.0,0,0,4,8,2130,780,1966,0,98006,1970,9000
4319,20141216T000000,432500.0,3,2.50,2390,6435,1.0,0,0,3,8,1600,790,1978,0,98034,2020,7300
9434,20140711T000000,665000.0,5,2.25,3320,60984,2.0,0,0,3,9,3320,0,2000,0,98045,1580,55322